[tools]
swiftlint = "0.63.2"

[tasks.lint]
description = "Lint Swift sources with SwiftLint"
run = "swiftlint lint --quiet --strict --config .swiftlint.yml"

[hooks]
postinstall = '''
set -e
chmod +x .git-hooks/*
git config --local core.hooksPath .git-hooks
'''
